# Generated by Django 5.2.9 on 2026-01-20 08:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_date', models.DateField(blank=True, null=True)),
                ('pid', models.CharField(max_length=255, unique=True)),
                ('hid', models.CharField(blank=True, max_length=255, null=True)),
                ('nid', models.CharField(blank=True, max_length=255, null=True)),
                ('fname', models.CharField(blank=True, max_length=255, null=True)),
                ('mname', models.CharField(blank=True, max_length=255, null=True)),
                ('lname', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=8, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('Se', 'Separated'), ('W', 'Widowed/Widower'), ('C', 'Cohabitating')], max_length=15, null=True)),
                ('education', models.CharField(blank=True, choices=[('1', 'Not Attended School'), ('2', 'Primary'), ('3', 'Secondary'), ('4', 'Certificate'), ('5', 'Diploma'), ('6', 'Undergraduate'), ('7', 'Postgraduate')], max_length=25, null=True)),
                ('occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_patient', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('phone_relative', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('ward', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_enrolled', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.site')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_date', models.DateField()),
                ('screening_status', models.CharField(choices=[('PASS', 'Passed'), ('FAIL', 'Failed'), ('PENDING', 'Pending')], max_length=10)),
                ('failure_reason', models.TextField(blank=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening', to='nimregenin.patient')),
                ('screened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField()),
                ('study_id', models.CharField(blank=True, max_length=50)),
                ('randomization_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('RANDOMIZED', 'Randomized'), ('WITHDRAWN', 'Withdrawn')], default='ENROLLED', max_length=15)),
                ('enrolled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('screening', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='nimregenin.screening')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('BASELINE', 'Baseline (Day 0)'), ('DAY7', 'Day 7'), ('DAY14', 'Day 14'), ('DAY30', 'Day 30'), ('DAY60', 'Day 60'), ('DAY90', 'Day 90'), ('DAY120', 'Day 120')], max_length=20)),
                ('planned_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='nimregenin.enrollment')),
            ],
            options={
                'ordering': ['planned_date'],
                'unique_together': {('enrollment', 'visit_type')},
            },
        ),
        migrations.CreateModel(
            name='CRF7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(blank=True, help_text='Date when efficacy was assessed', null=True)),
                ('primary_endpoint_score', models.DecimalField(blank=True, decimal_places=2, help_text='Primary efficacy endpoint score', max_digits=6, null=True)),
                ('secondary_endpoint_score', models.DecimalField(blank=True, decimal_places=2, help_text='Secondary endpoint score', max_digits=6, null=True)),
                ('clinician_global_impression', models.CharField(blank=True, help_text="Clinician's global impression of change", max_length=50)),
                ('patient_global_impression', models.CharField(blank=True, help_text="Patient's global impression of change", max_length=50)),
                ('clinician_assessment', models.TextField(blank=True, help_text="Clinician's detailed assessment")),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crf7', to='nimregenin.visit')),
            ],
            options={
                'verbose_name': 'CRF7 - Efficacy Assessment',
                'verbose_name_plural': 'CRF7 - Efficacy Assessments',
            },
        ),
        migrations.CreateModel(
            name='CRF6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(help_text='Date of final visit or termination')),
                ('early_termination', models.BooleanField(default=False, help_text='Check if patient exited study before Day 120')),
                ('termination_reason', models.CharField(blank=True, choices=[('COMPLETED', 'Completed 120 Days Follow-Up'), ('DEATH', 'Patient Died'), ('WITHDRAWN', 'Withdrew Consent'), ('LTFU', 'Lost to Follow-Up'), ('OTHER', 'Other')], help_text='Required if early termination', max_length=20)),
                ('other_reason', models.TextField(blank=True, help_text="Specify if 'Other' selected")),
                ('study_completion_status', models.CharField(choices=[('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated')], help_text='Final study status', max_length=20)),
                ('final_notes', models.TextField(blank=True, help_text='Any final comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(limit_choices_to={'visit_type__in': ['DAY120']}, on_delete=django.db.models.deletion.CASCADE, related_name='crf6', to='nimregenin.visit')),
            ],
            options={
                'verbose_name': 'CRF6 - Study Completion/Termination',
                'verbose_name_plural': 'CRF6 - Study Completion/Termination',
            },
        ),
        migrations.CreateModel(
            name='CRF5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(blank=True, help_text='Date when AE was reported', null=True)),
                ('ae_description', models.TextField(help_text='Description of the adverse event')),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], help_text='Severity grade', max_length=20)),
                ('serious', models.BooleanField(default=False, help_text='Is this a Serious Adverse Event?')),
                ('onset_date', models.DateField(help_text='Date AE started')),
                ('resolution_date', models.DateField(blank=True, help_text='Date AE resolved (if applicable)', null=True)),
                ('outcome', models.CharField(blank=True, help_text='Outcome of the AE', max_length=50)),
                ('relationship_to_study', models.CharField(blank=True, choices=[('RELATED', 'Related'), ('POSSIBLY_RELATED', 'Possibly Related'), ('NOT_RELATED', 'Not Related'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crf5_aes', to='nimregenin.visit')),
            ],
            options={
                'verbose_name': 'CRF5 - Adverse Event',
                'verbose_name_plural': 'CRF5 - Adverse Events',
                'ordering': ['-onset_date'],
            },
        ),
        migrations.CreateModel(
            name='CRF4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(blank=True, help_text='Date when medication list was recorded', null=True)),
                ('no_conmeds', models.BooleanField(default=False, help_text='Check if patient is not taking any concomitant medications')),
                ('medications', models.TextField(blank=True, help_text='List all current medications: name, dose, frequency, indication')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crf4', to='nimregenin.visit')),
            ],
            options={
                'verbose_name': 'CRF4 - Concomitant Medications',
                'verbose_name_plural': 'CRF4 - Concomitant Medications',
            },
        ),
        migrations.CreateModel(
            name='CRF3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(blank=True, help_text='Date when lab samples were taken', null=True)),
                ('hemoglobin', models.DecimalField(blank=True, decimal_places=2, help_text='g/dL', max_digits=5, null=True)),
                ('wbc', models.DecimalField(blank=True, decimal_places=2, help_text='×10³/µL', max_digits=6, null=True)),
                ('platelets', models.PositiveIntegerField(blank=True, help_text='×10³/µL', null=True)),
                ('creatinine', models.DecimalField(blank=True, decimal_places=2, help_text='mg/dL', max_digits=5, null=True)),
                ('alt', models.PositiveIntegerField(blank=True, help_text='U/L', null=True)),
                ('ast', models.PositiveIntegerField(blank=True, help_text='U/L', null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional lab notes or comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crf3', to='nimregenin.visit')),
            ],
            options={
                'verbose_name': 'CRF3 - Laboratory Results',
                'verbose_name_plural': 'CRF3 - Laboratory Results',
            },
        ),
        migrations.CreateModel(
            name='CRF2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(blank=True, help_text='Date when vital signs were taken', null=True)),
                ('systolic_bp', models.PositiveIntegerField(blank=True, help_text='mmHg', null=True)),
                ('diastolic_bp', models.PositiveIntegerField(blank=True, help_text='mmHg', null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, help_text='beats per minute', null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='°C', max_digits=4, null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, help_text='breaths per minute', null=True)),
                ('physical_exam_findings', models.TextField(blank=True, help_text='Any notable physical exam findings')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crf2', to='nimregenin.visit')),
            ],
            options={
                'verbose_name': 'CRF2 - Vital Signs',
                'verbose_name_plural': 'CRF2 - Vital Signs',
            },
        ),
        migrations.CreateModel(
            name='CRF1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=4, null=True)),
                ('medical_history', models.TextField(blank=True)),
                ('baseline_conmeds', models.TextField(blank=True, help_text='List of concomitant medications at baseline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('concomitant_medications', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(limit_choices_to={'visit_type': 'BASELINE'}, on_delete=django.db.models.deletion.CASCADE, related_name='crf1', to='nimregenin.visit')),
            ],
        ),
    ]
