# Generated by Django 5.2.9 on 2025-12-21 18:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], max_length=1)),
                ('ethnicity', models.CharField(blank=True, max_length=100)),
                ('race', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Demographics',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField()),
                ('study_id', models.CharField(blank=True, max_length=50)),
                ('randomization_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('RANDOMIZED', 'Randomized'), ('WITHDRAWN', 'Withdrawn')], default='ENROLLED', max_length=15)),
                ('enrolled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='nimregenin.demographic')),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_date', models.DateField()),
                ('screening_status', models.CharField(choices=[('PASS', 'Passed'), ('FAIL', 'Failed'), ('PENDING', 'Pending')], max_length=10)),
                ('failure_reason', models.TextField(blank=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening', to='nimregenin.demographic')),
                ('screened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('BASELINE', 'Baseline (Day 0)'), ('DAY7', 'Day 7'), ('DAY14', 'Day 14'), ('DAY30', 'Day 30'), ('DAY60', 'Day 60'), ('DAY90', 'Day 90'), ('DAY120', 'Day 120')], max_length=20)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='nimregenin.demographic')),
            ],
            options={
                'unique_together': {('patient', 'visit_type')},
            },
        ),
        migrations.CreateModel(
            name='CRF7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('early_termination', models.BooleanField(default=False)),
                ('termination_reason', models.TextField(blank=True)),
                ('study_completion_status', models.CharField(blank=True, choices=[('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.OneToOneField(limit_choices_to={'visit_type__in': ['DAY90', 'DAY120']}, on_delete=django.db.models.deletion.CASCADE, related_name='crf7', to='nimregenin.visit')),
            ],
        ),
        migrations.CreateModel(
            name='CRF6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('primary_endpoint_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('secondary_endpoint_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('clinician_assessment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crf6', to='nimregenin.visit')),
            ],
        ),
        migrations.CreateModel(
            name='CRF5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('medication_name', models.CharField(max_length=200)),
                ('dose', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crf5', to='nimregenin.visit')),
            ],
        ),
        migrations.CreateModel(
            name='CRF4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ae_start_date', models.DateField()),
                ('ae_description', models.TextField()),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], max_length=20)),
                ('serious', models.BooleanField(default=False)),
                ('outcome', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crf4', to='nimregenin.visit')),
            ],
        ),
        migrations.CreateModel(
            name='CRF3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('hemoglobin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wbc', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('platelets', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('creatinine', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alt', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('ast', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crf3', to='nimregenin.visit')),
            ],
        ),
        migrations.CreateModel(
            name='CRF2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('systolic_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('diastolic_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('physical_exam_findings', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crf2', to='nimregenin.visit')),
            ],
        ),
        migrations.CreateModel(
            name='CRF1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('medical_history', models.TextField(blank=True)),
                ('concomitant_medications', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.OneToOneField(limit_choices_to={'visit_type': 'BASELINE'}, on_delete=django.db.models.deletion.CASCADE, related_name='crf1', to='nimregenin.visit')),
            ],
        ),
    ]
