# Generated by Django 5.2.9 on 2026-01-20 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nimregenin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='enrolled_by',
        ),
    ]
