# Generated by Django 5.2.9 on 2025-12-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimregenin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crf3',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
