# Generated by Django 5.2.9 on 2025-12-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimregenin', '0002_alter_crf3_visit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf4',
            name='ae_start_date',
        ),
        migrations.AddField(
            model_name='crf4',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crf1',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crf2',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crf5',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crf6',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
