# Generated by Django 5.2.9 on 2026-01-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nimregenin', '0002_remove_enrollment_enrolled_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='screened_by',
        ),
    ]
