# Generated by Django 5.2.9 on 2025-12-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nimregenin', '0003_remove_crf4_ae_start_date_crf4_visit_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf5',
            name='dose',
        ),
        migrations.RemoveField(
            model_name='crf5',
            name='medication_name',
        ),
    ]
