# Generated by Django 5.2.9 on 2025-12-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimregenin', '0004_remove_crf5_dose_remove_crf5_medication_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf5',
            name='dose',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='crf5',
            name='medication_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
