# Generated by Django 5.2.9 on 2025-12-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimregenin', '0005_crf5_dose_crf5_medication_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographic',
            name='site',
            field=models.CharField(blank=True, choices=[('SITE001', 'Site 001 - City Hospital'), ('SITE002', 'Site 002 - University Medical Center'), ('SITE003', 'Site 003 - Regional Clinic'), ('SITE004', 'Site 004 - Private Practice')], max_length=200, null=True),
        ),
    ]
