# Generated by Django 5.2.9 on 2025-12-24 11:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimregenin', '0005_crf5_dose_crf5_medication_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demographic',
            options={'ordering': ['-created_at'], 'verbose_name': 'Patient Demographic', 'verbose_name_plural': 'Patient Demographics'},
        ),
        migrations.RenameField(
            model_name='demographic',
            old_name='date_of_birth',
            new_name='dob',
        ),
        migrations.RemoveField(
            model_name='demographic',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='demographic',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='demographic',
            name='race',
        ),
        migrations.AddField(
            model_name='demographic',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_enrolled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demographic',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demographic',
            name='education',
            field=models.CharField(blank=True, choices=[('1', 'Not Attended School'), ('2', 'Primary'), ('3', 'Secondary'), ('4', 'Certificate'), ('5', 'Diploma'), ('6', 'Undergraduate'), ('7', 'Postgraduate')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='demographic',
            name='fname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demographic',
            name='hid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demographic',
            name='lname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demographic',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('Se', 'Separated'), ('W', 'Widowed/Widower'), ('C', 'Cohabitating')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='demographic',
            name='mname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demographic',
            name='nid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demographic',
            name='occupation',
            field=models.CharField(blank=True, choices=[('1', 'Employed'), ('2', 'Self-Employed'), ('3', 'Business'), ('4', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='demographic',
            name='phone_patient',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', 'Enter a valid phone number.')]),
        ),
        migrations.AddField(
            model_name='demographic',
            name='phone_relative',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', 'Enter a valid phone number.')]),
        ),
        migrations.AddField(
            model_name='demographic',
            name='pid',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demographic',
            name='rec_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demographic',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demographic',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demographic',
            name='site',
            field=models.PositiveIntegerField(choices=[('1', 'MNH'), ('2', 'ORCI')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demographic',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demographic',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='demographic',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demographic',
            name='ward',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screening',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=8, null=True),
        ),
    ]
