# Generated by Django 5.2.9 on 2025-12-24 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimregenin', '0006_alter_demographic_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf1',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='crf1',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='crf2',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='crf2',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='crf3',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='crf3',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='crf4',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='crf4',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='crf5',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='crf5',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='crf6',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='crf6',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='crf7',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='crf7',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='crf1',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crf1', to='nimregenin.visit'),
        ),
        migrations.AlterField(
            model_name='crf7',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crf7', to='nimregenin.visit'),
        ),
    ]
