# Generated by Django 5.2.9 on 2025-12-22 00:35

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimregenin', '0006_demographic_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demographic',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Demographics'},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screening',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Patient age in years (0–120)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="Patient's date of birth", null=True),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='ethnicity',
            field=models.CharField(blank=True, help_text='Ethnicity (e.g., Hispanic or Latino)', max_length=100),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], help_text='Patient gender', max_length=1),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='patient_id',
            field=models.CharField(help_text='Unique patient identifier (e.g., PT-001)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='race',
            field=models.CharField(blank=True, help_text='Race (e.g., White, Asian, Black)', max_length=100),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='site',
            field=models.CharField(blank=True, choices=[('SITE001', 'Site 001 - City Hospital'), ('SITE002', 'Site 002 - University Medical Center'), ('SITE003', 'Site 003 - Regional Clinic'), ('SITE004', 'Site 004 - Private Practice')], help_text='Clinical site where patient is enrolled', max_length=20, null=True),
        ),
    ]
