# Generated by Django 5.2.9 on 2025-12-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimregenin', '0007_remove_crf1_created_at_remove_crf1_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographic',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
