# Generated by Django 5.2.9 on 2025-12-24 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('nimregenin', '0008_alter_demographic_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographic',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.site'),
        ),
    ]
