# Generated by Django 5.2.9 on 2026-01-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimregenin', '0009_crf3_updated_at_crf3_updated_by_crf4_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
