# Generated by Django 5.2.9 on 2025-12-31 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimregenin', '0009_alter_demographic_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='nimregenin.screening'),
        ),
    ]
