# Generated by Django 4.2.29 on 2026-03-15 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField()),
                ('consent_signed', models.BooleanField(default=False)),
                ('enrolled_by', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('lost', 'Lost To Follow Up'), ('transfer', 'Transferred Out')], default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VisitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_day', models.CharField(choices=[('D0', 'Day 0'), ('D7', 'Day 7'), ('D14', 'Day 14'), ('D30', 'Day 30'), ('D60', 'Day 60'), ('D90', 'Day 90'), ('D120', 'Day 120')], max_length=10)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('missed', 'Missed'), ('na', 'Not Applicable')], default='pending', max_length=20)),
                ('actual_visit_date', models.DateField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='herbal.enrollment')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('symptoms', models.TextField(blank=True)),
                ('adverse_events', models.TextField(blank=True)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='herbal.visitschedule')),
            ],
        ),
        migrations.CreateModel(
            name='UnscheduledVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unscheduled_visits', to='herbal.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_date', models.DateField()),
                ('age_eligible', models.BooleanField(default=False)),
                ('inclusion_criteria_met', models.BooleanField(default=False)),
                ('exclusion_criteria_present', models.BooleanField(default=False)),
                ('eligible', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening', to='herbal.subject')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='herbal.subject'),
        ),
        migrations.CreateModel(
            name='CRF7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigator_notes', models.TextField()),
                ('follow_up_needed', models.BooleanField(default=False)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crf7', to='herbal.visitschedule')),
            ],
        ),
        migrations.CreateModel(
            name='CRF6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_date', models.DateField()),
                ('reason', models.CharField(choices=[('completed', 'Completed Study'), ('lost_follow_up', 'Lost To Follow Up'), ('withdrawn', 'Participant Withdrew'), ('transfer_out', 'Transferred Out'), ('medical_reason', 'Medical Reason')], max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='termination', to='herbal.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='CRF5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('event_description', models.TextField()),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20)),
                ('action_taken', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverse_events', to='herbal.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='CRF4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_given', models.BooleanField(default=False)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('adherence', models.BooleanField(default=True)),
                ('comments', models.TextField(blank=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crf4', to='herbal.visitschedule')),
            ],
        ),
        migrations.CreateModel(
            name='CRF3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crf3', to='herbal.visitschedule')),
            ],
        ),
        migrations.CreateModel(
            name='CRF2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_result', models.TextField()),
                ('test_date', models.DateField()),
                ('comments', models.TextField(blank=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crf2', to='herbal.visitschedule')),
            ],
        ),
        migrations.CreateModel(
            name='CRF1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crf1', to='herbal.visitschedule')),
            ],
        ),
    ]
